[package]
name = "com-croftsoft-lib-role"
version = "0.1.5-SNAPSHOT"
authors = ["David Wallace Croft <david@croftsoft.com>"]
# Use the categories from https://crates.io/categories
# categories = ["category-name"]
description = "Reusable Rust traits"
edition = "2021"
homepage = "https://www.croftsoft.com/"
# keywords = ["keyword"]
# Remark this line out if your project is not open source
license = "MIT"
# Remark this line out when you publish to crates.io
publish = false
readme = "README.md"
# Remark this line out if your project is not in a code repository
repository = "https://github.com/david-wallace-croft/com-croftsoft-lib-role"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
